AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LF0:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::987936919727:role/service-role/LF0-role-h4894607'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /questions
            Method: OPTIONS
        Api3:
          Type: Api
          Properties:
            Path: /questions
            Method: POST
      Layers:
        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:3'
