AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::987936919727:role/service-role/LF1-role-n319iwq9'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /answers
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:3'
